---
- name: collect all nxapi test cases
  find:
    paths: "{{ role_path }}/tests/nxapi"
    patterns: "{{ testcase }}.yaml"
  register: test_cases

- name: set test_items
  set_fact: test_items="{{ test_cases.files | map(attribute='path') | list }}"

- name: enable nxapi
  nxos_config:
    lines:
      - feature nxapi
      - nxapi http port 80
    provider: "{{ cli }}"

- name: run test case
  include: "{{ item }}"
  with_items: "{{ test_items }}"

- name: disable nxapi
  nxos_config:
    lines:
      - no feature nxapi
    provider: "{{ cli }}"

